import React,{useState}from'react';
type Props={page:string;groups:any[];onNav:(id:string)=>void;onAdd:()=>void;collapsed:boolean;setCollapsed:(v:boolean)=>void;online:boolean};
const raw=(k:string,d='')=>{try{return localStorage.getItem(k)||d}catch{return d}};const json=<T,>(k:string,d:T):T=>{try{return JSON.parse(raw(k))}catch{return d}};
export function Sidebar({page,groups,onNav,onAdd,collapsed,setCollapsed,online}:Props){
 const[open,setOpen]=useState<Record<string,boolean>>({THE_JOURNEY:true,MY_MODEL:true,DEEPER:false,SYSTEM:false});
 const owner=raw('eil-access-mode','owner')==='owner',p=Number(raw('eil-journey-progress','1'));
 const item=([id,label,icon]:string[])=><button key={id} className={page===id?'sideLink active':'sideLink'} onClick={()=>onNav(id)}><i>{icon}</i>{!collapsed&&<span>{label}</span>}</button>;
 const visibleGroups=groups.map((group:any)=>({...group,items:group.items.filter(([id]:string[])=>owner||!['atlas','mentor','research','activity','settings'].includes(id))}));
 return <aside className={'sideRail '+(collapsed?'collapsed':'')}><div className="railGlow"/><div className="sideBrand"><button className="brandMark" onClick={()=>onNav('dashboard')}>E</button>{!collapsed&&<div><b>E.I.L</b><small>{owner?'CREATOR MODE':'THE JOURNEY'}</small></div>}<button className="collapseBtn" onClick={()=>setCollapsed(!collapsed)}>{collapsed?'‹':'›'}</button></div>{owner&&<button className="sideAdd" onClick={onAdd}><span>＋</span>{!collapsed&&<><b>הוסף מקור</b><small>מסמך · מאמר · מחשבה</small></>}</button>}{!collapsed&&<div className="journeyMini"><div><span>המסע</span><b>{owner?'פתוח':`${Math.min(p,18)} / 18`}</b></div><i><em style={{width:`${owner?100:p/18*100}%`}}/></i><small>למד → הבן → בדוק בחיים → חזור עם תצפית.</small></div>}<nav className="sideNav"><button className={page==='dashboard'?'sideLink active':'sideLink'} onClick={()=>onNav('dashboard')}><i>⌂</i>{!collapsed&&<span>היום</span>}</button>{visibleGroups.map((group:any)=>{const key=String(group.title).replace(/\s+/g,'_');const isOpen=collapsed||open[key]!==false;return group.items.length?<section className={'sideGroup flowGroup '+(isOpen?'isOpen':'')} key={group.title}>{!collapsed&&<button className="groupToggle" onClick={()=>setOpen(x=>({...x,[key]:!isOpen}))}><span>{group.title==='MY MODEL'?'השאלות שלי':group.title==='THE JOURNEY'?'המסע':group.title==='DEEPER'?'כלים עמוקים':'מערכת'}</span><b>{isOpen?'−':'+'}</b></button>}<div className="groupItems">{isOpen&&group.items.map(item)}</div></section>:null})}</nav><div className="sideUtilities"><span className={online?'pulse online':'pulse'}/>{!collapsed&&<small>{online?'מחובר למקורות':'מצב מקומי'}</small>}</div></aside>
}

type DashProps={onNav:(id:string)=>void;onAdd:()=>void;itemsCount:number;paragraphs:number;corpusReady:boolean};
export function EvolutionDashboard({onNav,onAdd,paragraphs,corpusReady}:DashProps){const owner=raw('eil-access-mode','owner')==='owner',p=Number(raw('eil-journey-progress','1')),focus=json<any>('eil-focus',null),origin=raw('eil-origin-answer','התשובה הראשונה שלך עדיין מחכה לך.');const pct=Math.round((Math.min(p,18)/18)*100);if(!owner&&p<7)return <div className="earlyDashboard"><span className="eyebrow">E.I.L / THE JOURNEY</span><h1>{p<=1?'השאלה עדיין פתוחה.':'כל תשובה פותחת שאלה חדשה.'}</h1><p>{p<=1?'לפני תובנות, פעולות ומדדים — בונים בסיס. מתחילים באדם כמכלול, ומתקדמים מהפיזי אל המופשט.':`הגעת לשכבה ${p}. עכשיו עדיין לא ממהרים להסיק מסקנות; בונים הקשר כדי שהתובנות שיגיעו אחר כך יהיו משמעותיות.`}</p><div className="earlyQuestion"><small>השאלה שמלווה את המסע</small><b>מי אני?</b><span>{origin}</span></div><button className="primary" onClick={()=>onNav('library')}>המשך לשכבה {p} ←</button></div>;
 return <div className="evolutionDash"><header className="dashIntro"><div><span className="eyebrow">E.I.L / AWARENESS</span><h1>מה נמצא בפרונט עכשיו?</h1><p>הדשבורד לא מודד כמה מידע צברת. הוא מחזיר אותך לשלוש שאלות: מה משפיע עליי, מה אני מבין, ומה אני בודק בחיים.</p></div>{owner&&<button className="quietAdd" onClick={onAdd}>＋ הוסף משהו שלמדתי</button>}</header><section className="dashboardJourneyGrid"><article className="identityGlass"><span className="heroKicker">THE QUESTION</span><h2>מי אני?</h2><p>{origin}</p><button className="ghostAction" onClick={()=>onNav('library')}>חזור למסע ←</button><div className="identityOrb">?</div></article><article className="progressGlass"><div className="progressHead"><div><span className="heroKicker">LEARNING PATH</span><h2>התקדמות במסע</h2></div><b>{owner?'פתוח':`${pct}%`}</b></div><div className="bigProgress"><i style={{width:`${owner?100:pct}%`}}/></div><div className="progressMeta"><span>{owner?'כל 18 השכבות זמינות':`${Math.min(p,18)} מתוך 18 שכבות נפתחו`}</span><button onClick={()=>onNav('library')}>המשך במסע ←</button></div></article></section><section className="liveStateGrid"><article className="liveStateCard active" onClick={()=>onNav('sources')}><span>01 / INPUT</span><h3>מה משפיע עליי?</h3><p>ראה את המקורות והחומר שמזינים את המודל שלך.</p></article><article className={'liveStateCard '+(focus?'active':'')} onClick={()=>onNav('insights')}><span>02 / UNDERSTANDING</span><h3>מה אני מבין?</h3><p>{focus?focus.topic:'חבר טענות וראיות לתובנה שאפשר לבדוק.'}</p></article><article className="liveStateCard active" onClick={()=>onNav('transformation')}><span>03 / PRACTICE</span><h3>מה אני בודק בחיים?</h3><p>העבר תובנה לניסוי קצר, חזור עם תצפית ותעד שינוי.</p></article></section><section className="signalStrip quietSignals"><button onClick={()=>onNav('library')}><strong>{owner?'18':p}</strong><span>שכבה נוכחית</span><small>מתוך 18</small></button><button onClick={()=>onNav('sources')}><strong>{paragraphs||'—'}</strong><span>פסקאות מקור</span><small>{corpusReady?'המקור המלא מחובר':'המקור נטען'}</small></button><button onClick={()=>onNav('transformation')}><strong>1</strong><span>Core Loop</span><small>Vertical Slice מוכן</small></button></section></div>
}
