import React,{useCallback,useEffect,useMemo,useState}from'react';

type QueueName='intake'|'duplicates'|'classification'|'epistemic'|'conflicts'|'relations'|'learning';
type Overview={counts:Record<QueueName,number>;learningHealth?:{strictDependencyCycles:number;candidateLearningUnits:number;sourceOrderUsed:boolean;fixedChapterCount:boolean}};
const queues:{id:QueueName;label:string;hint:string}[]=[
 {id:'intake',label:'חומרים חדשים',hint:'חומר שנבדק ומחכה להחלטה'},
 {id:'duplicates',label:'כפילויות',hint:'מושגים שנראים זהים ודורשים שיקול דעת'},
 {id:'classification',label:'סיווג',hint:'אטומים עם סיווג או confidence שדורשים בדיקה'},
 {id:'epistemic',label:'ראיה / תובנה / אמונה',hint:'הפרדה בין evidence, פרשנות, תובנה ותפיסת עולם'},
 {id:'conflicts',label:'סתירות',hint:'מתחים וטענות סותרות'},
 {id:'relations',label:'קשרים לא פתורים',hint:'קשרים עם endpoint שעדיין לא מופה'},
 {id:'learning',label:'סדר למידה',hint:'תלויות prerequisite / depends-on שמבקשות אישור'},
];
const atomTypes=['CLAIM','CONCEPT','DEFINITION','QUESTION','MODEL','EXAMPLE','PRACTICE','CREATOR_INSIGHT','WORLDVIEW_CLAIM','REFERENCE','TENSION','EDITORIAL_NOTE'];
const authHeaders=(key:string,extra:Record<string,string>={})=>({Authorization:`Bearer ${key}`,'X-EIL-Reviewer':'creator',...extra});
async function api<T>(url:string,key:string,options:RequestInit={}):Promise<T>{
 const response=await fetch(url,{...options,headers:{...authHeaders(key,options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));
 if(response.status===401)throw Object.assign(new Error('מפתח העורך אינו תקין'),{code:'EDITOR_AUTH_REQUIRED'});if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data as T;
}
function readStoredKey(){try{return sessionStorage.getItem('eil-editor-key')||''}catch{return''}}
function saveStoredKey(value:string){try{if(value)sessionStorage.setItem('eil-editor-key',value);else sessionStorage.removeItem('eil-editor-key')}catch{}}
function formatConfidence(value:any){const n=Number(value);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}
function verdictClass(value:string){return`reviewVerdict reviewVerdict--${String(value||'UNCERTAIN').toLowerCase()}`}
async function fileToBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result||'').split(',')[1]||'');reader.readAsDataURL(file)})}

export function ReviewConsole(){
 const[key,setKey]=useState(readStoredKey);const[inputKey,setInputKey]=useState('');const[overview,setOverview]=useState<Overview|null>(null);const[queue,setQueue]=useState<QueueName>('intake');const[items,setItems]=useState<any[]>([]);const[queueHealth,setQueueHealth]=useState<any>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const[newTitle,setNewTitle]=useState('');const[newText,setNewText]=useState('');const[newUrl,setNewUrl]=useState('');const[newFile,setNewFile]=useState<File|null>(null);const[newAnalysis,setNewAnalysis]=useState<any>(null);const[showNew,setShowNew]=useState(true);
 const unlocked=Boolean(key&&overview);
 const loadOverview=useCallback(async(activeKey=key)=>{if(!activeKey)return;setLoading(true);setError('');try{const data=await api<any>('/api/editor?queue=overview',activeKey);setOverview(data);saveStoredKey(activeKey)}catch(e:any){setOverview(null);setError(e.message);if(e.code==='EDITOR_AUTH_REQUIRED'){setKey('');saveStoredKey('')}}finally{setLoading(false)}},[key]);
 const loadQueue=useCallback(async(activeQueue=queue,activeKey=key)=>{if(!activeKey)return;setLoading(true);setError('');try{const data=await api<any>(`/api/editor?queue=${activeQueue}&limit=60`,activeKey);setItems(data.items||[]);setQueueHealth(data.health||null)}catch(e:any){setError(e.message);if(e.code==='EDITOR_AUTH_REQUIRED'){setKey('');setOverview(null);saveStoredKey('')}}finally{setLoading(false)}},[key,queue]);
 useEffect(()=>{if(key&&!overview)void loadOverview(key)},[key,overview,loadOverview]);
 useEffect(()=>{if(unlocked)void loadQueue(queue,key)},[queue,unlocked,key,loadQueue]);
 const unlock=async(event:React.FormEvent)=>{event.preventDefault();const candidate=inputKey.trim();if(!candidate)return;setKey(candidate);setInputKey('');await loadOverview(candidate)};
 const logout=()=>{setKey('');setOverview(null);setItems([]);saveStoredKey('')};
 const refresh=async()=>{await Promise.all([loadOverview(key),loadQueue(queue,key)])};
 const decide=async(body:any)=>{setLoading(true);setError('');try{await api('/api/editor?queue='+queue,key,{method:'PATCH',body:JSON.stringify(body)});setNotice('ההחלטה נשמרה');await refresh()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const decideIntake=async(id:string,action:'APPROVE'|'REJECT'|'CHANGE',overrides:any={})=>{setLoading(true);setError('');try{await api(`/api/intake?id=${id}`,key,{method:'PATCH',body:JSON.stringify({action,reviewedBy:'creator',overrides})});setNotice(action==='APPROVE'?'המקור אושר ונכנס לשכבת הידע לבדיקה':action==='REJECT'?'החומר נדחה':'התיקון נשמר');await refresh()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const analyzeNew=async(event:React.FormEvent)=>{event.preventDefault();if(!newText.trim()&&!newUrl.trim()&&!newFile){setError('הדבק טקסט/URL או בחר קובץ');return}setLoading(true);setError('');setNewAnalysis(null);try{const body:any={title:newTitle.trim()||undefined,text:newText.trim()||undefined,url:newUrl.trim()||undefined};if(newFile){body.fileName=newFile.name;body.mimeType=newFile.type||'application/octet-stream';body.fileBase64=await fileToBase64(newFile)}const data=await api<any>('/api/intake',key,{method:'POST',body:JSON.stringify(body)});setNewAnalysis(data);setNotice('הניתוח הושלם ונשמר ב־Review Queue');await refresh()}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const total=useMemo(()=>overview?Object.values(overview.counts||{}).reduce((sum,n)=>sum+Number(n||0),0):0,[overview]);
 if(!unlocked)return <main className="reviewConsole reviewConsole--locked" dir="rtl"><section className="reviewLock"><span className="reviewEyebrow">E.I.L / CREATOR CONSOLE</span><h1>מרכז בקרת הידע</h1><p>המסך הזה מיועד לעורך בלבד. המפתח נשמר רק ב־session של הלשונית הנוכחית.</p><form onSubmit={unlock}><label>מפתח עורך<input type="password" autoComplete="current-password" value={inputKey} onChange={e=>setInputKey(e.target.value)} placeholder="הדבק את מפתח העורך"/></label><button disabled={loading}>{loading?'בודק…':'פתח את הקונסול'}</button></form>{error&&<div className="reviewError">{error}</div>}</section></main>;
 return <main className="reviewConsole" dir="rtl">
  <header className="reviewHeader"><div><span className="reviewEyebrow">E.I.L / CORPUS REVIEW</span><h1>מרכז בקרת הידע</h1><p>רק החלטות שדורשות שיקול דעת אנושי. שום merge קנוני או סדר לימוד לא מתבצע אוטומטית.</p></div><div className="reviewHeaderActions"><span>{total} החלטות פתוחות</span><button onClick={()=>setShowNew(v=>!v)}>{showNew?'סגור בדיקת חומר':'＋ בדוק חומר חדש'}</button><button className="reviewGhost" onClick={logout}>נעל</button></div></header>
  {notice&&<button className="reviewNotice" onClick={()=>setNotice('')}>{notice} ×</button>}{error&&<div className="reviewError">{error}</div>}
  {showNew&&<section className="reviewNew"><div className="reviewSectionTitle"><div><span className="reviewEyebrow">NEW INPUT</span><h2>בדוק חומר חדש מול המאגר</h2></div><p>נושא, מאמר, URL, PDF, DOCX או קובץ טקסט. תמונה דורשת כרגע גם תיאור טקסטואלי.</p></div><form onSubmit={analyzeNew} className="reviewNewForm"><input value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="כותרת (אופציונלי)"/><input value={newUrl} onChange={e=>setNewUrl(e.target.value)} placeholder="https://… (אופציונלי)" dir="ltr"/><textarea value={newText} onChange={e=>setNewText(e.target.value)} placeholder="הדבק נושא, טקסט, הערה או תיאור של תמונה…"/><label className="reviewFile">קובץ<input type="file" onChange={e=>setNewFile(e.target.files?.[0]||null)} accept=".pdf,.docx,.txt,.md,.csv,.json,.html,.xml,image/*"/><span>{newFile?.name||'לא נבחר קובץ'}</span></label><button disabled={loading}>{loading?'מנתח…':'בדוק מול המאגר'}</button></form>{newAnalysis&&<AnalysisResult analysis={newAnalysis} onApprove={()=>newAnalysis.staging?.id&&decideIntake(newAnalysis.staging.id,'APPROVE')} onReject={()=>newAnalysis.staging?.id&&decideIntake(newAnalysis.staging.id,'REJECT')}/>}</section>}
  <section className="reviewStats">{queues.map(q=><button key={q.id} className={queue===q.id?'active':''} onClick={()=>setQueue(q.id)}><strong>{overview?.counts?.[q.id]??0}</strong><span>{q.label}</span><small>{q.hint}</small></button>)}</section>
  {queue==='learning'&&(queueHealth||overview?.learningHealth)&&<div className="reviewHealth"><b>Learning Graph</b><span>cycles: {(queueHealth||overview?.learningHealth)?.strictDependencyCycles??0}</span><span>units: {(queueHealth||overview?.learningHealth)?.candidateLearningUnits??0}</span><span>file-order: {(queueHealth||overview?.learningHealth)?.sourceOrderUsed?'כן':'לא'}</span><span>fixed chapters: {(queueHealth||overview?.learningHealth)?.fixedChapterCount?'כן':'לא'}</span></div>}
  <section className="reviewQueue"><div className="reviewQueueHead"><div><span className="reviewEyebrow">{queue.toUpperCase()}</span><h2>{queues.find(q=>q.id===queue)?.label}</h2></div><button className="reviewGhost" onClick={()=>refresh()} disabled={loading}>רענן</button></div>{loading&&!items.length?<p>טוען…</p>:!items.length?<div className="reviewEmpty">אין כרגע החלטות פתוחות בתור הזה.</div>:<div className="reviewCards">{items.map((item,index)=><ReviewCard key={item.id||item.subjectKey||index} queue={queue} item={item} disabled={loading} onDecision={decide} onIntake={decideIntake}/>)}</div>}</section>
 </main>;
}

function AnalysisResult({analysis,onApprove,onReject}:{analysis:any;onApprove:()=>void;onReject:()=>void}){const verdict=analysis.verdict||{};return <div className="analysisResult"><div className="analysisTop"><span className={verdictClass(verdict.verdict)}>{verdict.verdict}</span><b>{formatConfidence(verdict.confidence)}</b><p>{verdict.reason}</p></div><div className="analysisGrid"><div><small>מקום מוצע</small><strong>{analysis.placement?.suggestedDrawer?.label||'עדיין לא ברור'}</strong><span>{formatConfidence(analysis.placement?.suggestedDrawer?.confidence)}</span></div><div><small>חדש</small><strong>{analysis.newMaterial?.count??0}</strong><span>אטומים</span></div><div><small>סתירות</small><strong>{analysis.conflicts?.count??0}</strong><span>לבדיקה</span></div><div><small>נותח</small><strong>{analysis.atomic?.analyzed??0}</strong><span>יחידות ידע</span></div></div>{analysis.closestExistingKnowledge?.length>0&&<div className="analysisMatches"><h3>הכי קרוב במאגר</h3>{analysis.closestExistingKnowledge.slice(0,4).map((m:any)=><div key={`${m.authority}-${m.id}`}><b>{m.text}</b><span>{m.sourceFile||m.sourceTitle||m.authority} · {formatConfidence(m.score)}</span></div>)}</div>}<div className="reviewActions"><button onClick={onApprove}>אשר והכנס כמקור</button><button className="danger" onClick={onReject}>דחה</button></div></div>}
function ReviewCard({queue,item,disabled,onDecision,onIntake}:{queue:QueueName;item:any;disabled:boolean;onDecision:(body:any)=>void;onIntake:(id:string,action:'APPROVE'|'REJECT'|'CHANGE',overrides?:any)=>void}){
 const[type,setType]=useState(item.type||'CLAIM');const[fromNode,setFromNode]=useState('');const[toNode,setToNode]=useState('');
 if(queue==='intake')return <article className="reviewCard"><CardMeta source={item.fileName||item.sourceUrl} confidence={item.verdict?.confidence}/><div className="reviewCardTitle"><span className={verdictClass(item.verdict?.verdict)}>{item.verdict?.verdict||'UNCERTAIN'}</span><h3>{item.title||'ללא כותרת'}</h3></div><p>{item.verdict?.reason}</p><div className="reviewFacts"><span>מקום: <b>{item.suggestedDrawer?.label||'לא הוכרע'}</b></span><span>חדש: <b>{item.newMaterial?.count??0}</b></span><span>סתירות: <b>{item.conflicts?.count??0}</b></span></div><div className="reviewActions"><button disabled={disabled} onClick={()=>onIntake(item.id,'APPROVE')}>אשר מקור</button><button className="danger" disabled={disabled} onClick={()=>onIntake(item.id,'REJECT')}>דחה</button></div></article>;
 if(queue==='duplicates')return <article className="reviewCard"><div className="reviewCardTitle"><span className="reviewBadge">{item.count} מופעים</span><h3>{item.label}</h3></div><div className="reviewDuplicateList">{item.items.map((x:any)=><div key={x.id}><b>{x.text}</b><span>{x.sourceFile||x.sourceTitle} · {formatConfidence(x.confidence)}</span></div>)}</div><div className="reviewActions"><button disabled={disabled} onClick={()=>onDecision({subjectKey:item.subjectKey,action:'MERGE',payload:{normalized:item.normalized,candidateIds:item.items.map((x:any)=>x.id)}})}>אותו מושג</button><button className="reviewGhost" disabled={disabled} onClick={()=>onDecision({subjectKey:item.subjectKey,action:'KEEP_SEPARATE',payload:{normalized:item.normalized,candidateIds:item.items.map((x:any)=>x.id)}})}>השאר נפרד</button></div></article>;
 if(queue==='relations'||queue==='learning'||(queue==='conflicts'&&item.kind==='RELATION')){const qKind=queue==='conflicts'?'RELATION':undefined;return <article className="reviewCard"><CardMeta source={item.sourceFile||item.sourceTitle} confidence={item.confidence}/><div className="reviewCardTitle"><span className="reviewBadge">{item.type}</span><h3>{item.from?.label||item.fromLabel} ← {item.to?.label||item.toLabel}</h3></div><blockquote>{item.quote}</blockquote>{item.cue&&<p>cue: <b>{item.cue}</b></p>}{item.from?.suggestions?.length>0&&<label>מיפוי צד א׳<select value={fromNode} onChange={e=>setFromNode(e.target.value)}><option value="">בחר…</option>{item.from.suggestions.map((s:any)=><option value={s.nodeId} key={s.nodeId}>{s.label} ({Math.round(s.score*100)}%)</option>)}</select></label>}{item.to?.suggestions?.length>0&&<label>מיפוי צד ב׳<select value={toNode} onChange={e=>setToNode(e.target.value)}><option value="">בחר…</option>{item.to.suggestions.map((s:any)=><option value={s.nodeId} key={s.nodeId}>{s.label} ({Math.round(s.score*100)}%)</option>)}</select></label>}<div className="reviewActions">{(fromNode||toNode)&&<button disabled={disabled} onClick={()=>onDecision({id:item.id,action:'RESOLVE',payload:{kind:qKind,fromNodeId:fromNode||undefined,toNodeId:toNode||undefined}})}>שמור מיפוי</button>}<button disabled={disabled||item.endpointResolution!=='MAPPED'} onClick={()=>onDecision({id:item.id,action:'APPROVE',payload:{kind:qKind}})}>אשר קשר</button><button className="danger" disabled={disabled} onClick={()=>onDecision({id:item.id,action:'REJECT',payload:{kind:qKind}})}>דחה</button></div></article>}
 return <article className="reviewCard"><CardMeta source={item.sourceFile||item.sourceTitle} confidence={item.confidence}/><div className="reviewCardTitle"><span className="reviewBadge">{item.type}</span><h3>{item.text}</h3></div>{item.section&&<p>הקשר: {item.section}</p>}<blockquote>{item.quote}</blockquote><div className="reviewClassify"><select value={type} onChange={e=>setType(e.target.value)}>{atomTypes.map(t=><option value={t} key={t}>{t}</option>)}</select><button className="reviewGhost" disabled={disabled||type===item.type} onClick={()=>onDecision({id:item.id,action:'CHANGE',payload:{atomType:type,claimType:item.claimType||null,kind:item.kind}})}>שנה סיווג</button></div><div className="reviewActions"><button disabled={disabled} onClick={()=>onDecision({id:item.id,action:'APPROVE',payload:{kind:item.kind}})}>אשר</button><button className="danger" disabled={disabled} onClick={()=>onDecision({id:item.id,action:'REJECT',payload:{kind:item.kind}})}>דחה</button></div></article>;
}
function CardMeta({source,confidence}:{source?:string;confidence?:any}){return <div className="reviewMeta"><span>{source||'מקור לא צוין'}</span><span>confidence {formatConfidence(confidence)}</span></div>}
