import React,{useMemo,useState}from'react';
import{assignmentRepository}from'./model/assignment.repository';
import{proposeTaxonomy,RESEARCH_INBOX,taxonomyTopics}from'./model/taxonomy';

type Chapter={number:number;title:string;subtitle:string;sourceFile:string;paragraphs:string[]};
type Props={chapters:Chapter[];onAdd:()=>void};
type Card={id:string;chapter:number;source:string;text:string;proposal:ReturnType<typeof proposeTaxonomy>};

export function ResearchWorkbench({chapters,onAdd}:Props){
 const[version,setVersion]=useState(0),[activeTopic,setActiveTopic]=useState('all');
 const cards=useMemo<Card[]>(()=>chapters.flatMap(chapter=>chapter.paragraphs.map((text,index)=>({id:`chapter-${chapter.number}-paragraph-${index+1}`,chapter:chapter.number,source:chapter.sourceFile,text:text.trim(),proposal:proposeTaxonomy(text)})).filter(card=>card.text)),[chapters]);
 const assignments=useMemo(()=>new Map(assignmentRepository.list().map(item=>[item.fragmentId,item])),[version]);
 const effective=(card:Card)=>assignments.get(card.id)?.topicId||card.proposal[0]?.topicId||RESEARCH_INBOX;
 const visible=activeTopic==='all'?cards:cards.filter(card=>effective(card)===activeTopic);
 const move=(card:Card,topicId:string,approved=false)=>{const previous=assignments.get(card.id);assignmentRepository.upsert({fragmentId:card.id,topicId:topicId||RESEARCH_INBOX,subtopic:previous?.subtopic||'',approved});setVersion(v=>v+1)};
 const approve=(card:Card)=>move(card,effective(card),true);
 const counts=taxonomyTopics.reduce<Record<string,number>>((acc,topic)=>({...acc,[topic.id]:cards.filter(card=>effective(card)===topic.id).length}),{});
 return <div className="researchWorkbench"><header className="researchHero"><div><span className="eyebrow">CREATIVE STRUCTURING WORKBENCH</span><h1>לסדר בלי לאבד את הקול.</h1><p>המערכת מציעה מגירות לפי מילות מפתח מתוך האונטולוגיה הקיימת. זו הצעה בלבד — לא אמת ולא סיווג AI מומצא. אתה מאשר, משנה או גורר לפני שהשיוך נחשב מאושר.</p></div><button className="primary" onClick={onAdd}>＋ העלה מקור / PDF</button></header><section className="researchStats"><div><b>{cards.length}</b><span>כרטיסיות מקור</span></div><div><b>{assignments.size}</b><span>שיוכים שנגעת בהם</span></div><div><b>{[...assignments.values()].filter(item=>item.approved).length}</b><span>שיוכים מאושרים</span></div></section><div className="researchLayout"><aside className="taxonomyRail"><button className={activeTopic==='all'?'active':''} onClick={()=>setActiveTopic('all')}><span>כל המגירות</span><b>{cards.length}</b></button>{taxonomyTopics.map(topic=><button key={topic.id} className={activeTopic===topic.id?'active':''} onClick={()=>setActiveTopic(topic.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>{const id=event.dataTransfer.getData('text/plain');const card=cards.find(item=>item.id===id);if(card)move(card,topic.id,true)}}><span>{topic.label}</span><b>{counts[topic.id]||0}</b></button>)}</aside><main className="researchBoard">{visible.slice(0,120).map(card=>{const assignment=assignments.get(card.id),topicId=effective(card),proposal=card.proposal[0];return <article className="researchCard" key={card.id} draggable onDragStart={event=>event.dataTransfer.setData('text/plain',card.id)}><header><span>פרק {String(card.chapter).padStart(2,'0')}</span><em>{assignment?.approved?'מאושר':'הצעה'}</em></header><p>{card.text}</p><div className="proposalLine"><div><small>מגירה מוצעת</small><b>{taxonomyTopics.find(topic=>topic.id===topicId)?.label||'מגירת ביניים'}</b></div><span>{proposal?Math.round(proposal.confidence*100):0}%</span></div>{proposal?.matchedTerms.length>0&&<small className="matchedTerms">נמצא בטקסט: {proposal.matchedTerms.join(' · ')}</small>}<footer><select value={topicId} onChange={event=>move(card,event.target.value,false)}>{taxonomyTopics.map(topic=><option key={topic.id} value={topic.id}>{topic.label}</option>)}</select><button className="secondary" onClick={()=>approve(card)}>{assignment?.approved?'✓ מאושר':'אשר שיוך'}</button></footer><small className="researchSource">{card.source} · {card.id.split('-').at(-1)}</small></article>})}</main></div></div>;
}
