import crypto from'node:crypto';
import{normalizeKnowledgeText}from'../matching/knowledge-overlap.service.js';
import{buildEmergentCorpusMapPreview}from'../map/emergent-corpus-map.service.js';
import{previewLearningDependencyGraph}from'../learning/learning-dependency.service.js';
import{rankRelationEndpointSuggestions}from'../relations/relation-endpoint-suggestions.service.js';

const sha256=value=>crypto.createHash('sha256').update(String(value)).digest('hex');
const REVIEW_QUEUES=new Set(['intake','duplicates','classification','epistemic','conflicts','relations','learning']);
const ATOM_TYPES=new Set(['CLAIM','CONCEPT','DEFINITION','QUESTION','MODEL','EXAMPLE','PRACTICE','CREATOR_INSIGHT','WORLDVIEW_CLAIM','REFERENCE','TENSION','EDITORIAL_NOTE']);
const CLAIM_TYPES=new Set(['FACTUAL','INTERPRETIVE','CAUSAL','NORMATIVE','DEFINITIONAL','EXPERIENTIAL','HYPOTHESIS']);
const ENDPOINT_KINDS=new Set(['CONCEPT','SECTION_TOPIC','SOURCE_SPAN']);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const NODE_KEY=/^[0-9a-f]{64}$/i;

async function tableReady(db,name){return Boolean((await db.query(`SELECT to_regclass($1) AS table_name`,[`public.${name}`])).rows[0]?.table_name)}
async function decision(db,{queueType,subjectType,subjectKey,action,payload={},reviewer}){
 if(!await tableReady(db,'review_decisions'))throw Object.assign(new Error('review decision schema is not ready'),{status:503,code:'REVIEW_SCHEMA_NOT_READY'});
 return(await db.query(`INSERT INTO review_decisions(queue_type,subject_type,subject_key,action,payload,reviewer) VALUES($1,$2,$3,$4,$5::jsonb,$6) RETURNING id,created_at`,[queueType,subjectType,subjectKey,action,JSON.stringify(payload||{}),reviewer])).rows[0];
}
function limitValue(value,fallback=50){return Math.max(1,Math.min(200,Number(value)||fallback))}
function extractionView(row){return{id:row.id,type:row.atom_type,claimType:row.claim_type,text:row.candidate_text,quote:row.exact_quote,confidence:Number(row.confidence),reviewStatus:row.review_status,sourceId:row.source_id,sourceTitle:row.source_title,sourceFile:row.source_file||null,section:row.section||null,signals:row.signals||[],createdAt:row.created_at}}
async function extractionRows(db,where='',params=[],limit=50){return(await db.query(`
 SELECT c.id,c.atom_type,c.claim_type,c.candidate_text,c.exact_quote,c.confidence,c.review_status,c.source_id,c.created_at,
        c.metadata->>'section' AS section,COALESCE(c.metadata->'signals','[]'::jsonb) AS signals,
        s.title AS source_title,COALESCE(s.metadata->>'sourceFile',s.metadata->>'originalFileName') AS source_file
 FROM extraction_candidates c JOIN sources s ON s.id=c.source_id
 WHERE c.review_status='PENDING' AND NOT c.exclude_from_knowledge ${where}
 ORDER BY CASE WHEN c.confidence<0.65 THEN 0 ELSE 1 END,c.confidence ASC,c.created_at ASC LIMIT $${params.length+1}
`,[...params,limitValue(limit)])).rows}
function intakeSummary(row){const a=row.analysis||{};return{id:row.id,title:row.title,inputKind:row.input_kind,fileName:row.file_name,sourceUrl:row.source_url,createdAt:row.created_at,verdict:a.verdict||null,suggestedDrawer:a.placement?.suggestedDrawer||null,byType:a.atomic?.byType||{},byVerdict:a.atomic?.byVerdict||{},closestExisting:(a.closestExistingKnowledge||[]).slice(0,4),newMaterial:a.newMaterial||null,conflicts:a.conflicts||null,learning:a.learning?{available:a.learning.available,suggestedUnits:(a.learning.suggestedUnits||[]).slice(0,4),spiralContext:(a.learning.spiralContext||[]).slice(0,3)}:null}}
async function intakeQueue(db,limit){if(!await tableReady(db,'intake_submissions'))return[];return(await db.query(`SELECT id,input_kind,title,source_url,file_name,analysis,created_at FROM intake_submissions WHERE review_status='PENDING' ORDER BY created_at ASC LIMIT $1`,[limitValue(limit)])).rows.map(intakeSummary)}
async function duplicateQueue(db,limit){
 const rows=(await db.query(`SELECT c.id,c.candidate_text,c.confidence,c.source_id,s.title source_title,COALESCE(s.metadata->>'sourceFile',s.metadata->>'originalFileName') source_file FROM extraction_candidates c JOIN sources s ON s.id=c.source_id WHERE c.atom_type='CONCEPT' AND c.review_status<>'REJECTED' AND NOT c.exclude_from_knowledge ORDER BY c.created_at`)).rows,groups=new Map();
 for(const row of rows){const normalized=normalizeKnowledgeText(row.candidate_text);if(!normalized)continue;const list=groups.get(normalized)||[];list.push(row);groups.set(normalized,list)}
 const candidates=[...groups.entries()].filter(([,items])=>items.length>1).map(([normalized,items])=>({subjectKey:sha256(`duplicate:${normalized}`),normalized,label:items[0].candidate_text,count:items.length,items:items.map(item=>({id:item.id,text:item.candidate_text,confidence:Number(item.confidence),sourceId:item.source_id,sourceTitle:item.source_title,sourceFile:item.source_file||null}))}));
 if(!candidates.length)return[];const keys=candidates.map(item=>item.subjectKey),decided=new Set((await db.query(`SELECT DISTINCT subject_key FROM review_decisions WHERE queue_type='DUPLICATE' AND subject_key=ANY($1::text[])`,[keys])).rows.map(row=>row.subject_key));return candidates.filter(item=>!decided.has(item.subjectKey)).slice(0,limitValue(limit));
}
async function classificationQueue(db,limit){const rows=await extractionRows(db,`AND (c.confidence<0.78 OR c.atom_type IN ('WORLDVIEW_CLAIM','CREATOR_INSIGHT','TENSION'))`,[],limit);return rows.map(extractionView)}
async function epistemicQueue(db,limit){const rows=await extractionRows(db,`AND (
 c.atom_type IN ('WORLDVIEW_CLAIM','CREATOR_INSIGHT')
 OR c.claim_type IN ('NORMATIVE','EXPERIENTIAL','INTERPRETIVE')
 OR COALESCE(c.metadata->>'section','') ~* '(חוקי?[ _]היקום|רוחני|הבורא|אלוהים|בריאה|נשמה|השגחה)'
 OR COALESCE(s.metadata->>'sourceFile',s.metadata->>'originalFileName','') ~* '(חוקי?[ _]היקום|רוחני|הבורא|אלוהים|בריאה|נשמה|השגחה)'
 OR c.candidate_text ~* '(הבורא|אלוהים|תכלית הבריאה|חוקי?[ _]היקום|חוק המשיכה|התודעה אינה נעלמת)'
)`,[],limit);return rows.map(extractionView)}
async function conflictQueue(db,limit){
 const atoms=(await extractionRows(db,`AND c.atom_type='TENSION'`,[],Math.ceil(limitValue(limit)/2))).map(row=>({kind:'ATOM',...extractionView(row)}));
 const relations=(await db.query(`SELECT r.id,r.relation_type,r.from_label,r.to_label,r.endpoint_resolution,r.cue,r.exact_quote,r.confidence,r.source_id,s.title source_title,COALESCE(s.metadata->>'sourceFile',s.metadata->>'originalFileName') source_file FROM relation_candidates r JOIN sources s ON s.id=r.source_id WHERE r.review_status='PENDING' AND r.relation_type='CONTRADICTS' ORDER BY r.confidence DESC,r.created_at LIMIT $1`,[Math.ceil(limitValue(limit)/2)])).rows.map(row=>({kind:'RELATION',id:row.id,type:row.relation_type,fromLabel:row.from_label,toLabel:row.to_label,endpointResolution:row.endpoint_resolution,cue:row.cue,quote:row.exact_quote,confidence:Number(row.confidence),sourceId:row.source_id,sourceTitle:row.source_title,sourceFile:row.source_file||null}));
 return[...atoms,...relations].slice(0,limitValue(limit));
}
async function mapRecords(db){const map=await buildEmergentCorpusMapPreview(db,{communityLimit:300,nodeLimit:700,edgeLimit:1500});return{map}}
function suggestionHealth(items){const bands={STRONG:0,PLAUSIBLE:0,AMBIGUOUS:0,WEAK:0,NONE:0},bySide={from:0,to:0};let unresolvedEndpoints=0;for(const item of items||[])for(const side of ['from','to']){const endpoint=item[side];if(!endpoint||endpoint.resolution==='MAPPED')continue;unresolvedEndpoints+=1;bySide[side]+=1;const band=endpoint.suggestionAssessment?.band||'NONE';bands[band]=(bands[band]||0)+1}return{unresolvedEndpoints,bands,bySide,strongShare:unresolvedEndpoints?Number((bands.STRONG/unresolvedEndpoints).toFixed(4)):0}}
async function relationQueue(db,limit,{learningOnly=false}={}){
 const where=learningOnly?`AND r.relation_type IN ('PREREQUISITE_FOR','DEPENDS_ON')`:`AND r.endpoint_resolution<>'MAPPED'`,rows=(await db.query(`SELECT r.id,r.relation_type,r.from_node_key,r.from_kind,r.from_label,r.from_resolution,r.to_node_key,r.to_kind,r.to_label,r.to_resolution,r.endpoint_resolution,r.cue,r.exact_quote,r.confidence,r.source_id,s.title source_title,COALESCE(s.metadata->>'sourceFile',s.metadata->>'originalFileName') source_file FROM relation_candidates r JOIN sources s ON s.id=r.source_id WHERE r.review_status='PENDING' ${where} ORDER BY CASE r.endpoint_resolution WHEN 'UNRESOLVED' THEN 0 WHEN 'PARTIAL' THEN 1 ELSE 2 END,r.confidence DESC,r.created_at LIMIT $1`,[limitValue(limit)])).rows;
 if(!rows.length)return[];const{map}=await mapRecords(db);return rows.map(row=>{const fromResult=row.from_resolution==='MAPPED'?{assessment:{band:'MAPPED',topScore:1,margin:1,recommendedNodeId:row.from_node_key,reason:'Endpoint is already mapped by creator review.'},suggestions:[]}:rankRelationEndpointSuggestions(row.from_label,map.nodes,{sourceFile:row.source_file,limit:5}),toResult=row.to_resolution==='MAPPED'?{assessment:{band:'MAPPED',topScore:1,margin:1,recommendedNodeId:row.to_node_key,reason:'Endpoint is already mapped by creator review.'},suggestions:[]}:rankRelationEndpointSuggestions(row.to_label,map.nodes,{sourceFile:row.source_file,limit:5});return{id:row.id,type:row.relation_type,from:{nodeId:row.from_node_key,kind:row.from_kind,label:row.from_label,resolution:row.from_resolution,suggestions:fromResult.suggestions,suggestionAssessment:fromResult.assessment},to:{nodeId:row.to_node_key,kind:row.to_kind,label:row.to_label,resolution:row.to_resolution,suggestions:toResult.suggestions,suggestionAssessment:toResult.assessment},endpointResolution:row.endpoint_resolution,cue:row.cue,quote:row.exact_quote,confidence:Number(row.confidence),sourceId:row.source_id,sourceTitle:row.source_title,sourceFile:row.source_file||null}})}
async function learningQueue(db,limit){const relations=await relationQueue(db,limit,{learningOnly:true}),graph=await previewLearningDependencyGraph(db,{unitLimit:250,spiralLimit:250,dependencyLimit:500});return{relations,health:{strictDependencyCycles:graph.summary?.strictCycles??0,candidateLearningUnits:graph.summary?.learningUnits??graph.learningUnits?.length??0,sourceOrderUsed:graph.method?.sourceOrderUsed??false,fixedChapterCount:graph.method?.fixedChapterCount??false,requiresApprovedRelations:graph.method?.requiresApprovedRelations??graph.policy?.requiresApprovedRelations??false}}}
export async function reviewOverview(db){
 const [intake,classification,epistemic,conflicts,relations,learning,duplicates]=await Promise.all([intakeQueue(db,200),classificationQueue(db,200),epistemicQueue(db,200),conflictQueue(db,200),relationQueue(db,200),learningQueue(db,200),duplicateQueue(db,200)]);
 return{ok:true,version:'review-console-v0.2',counts:{intake:intake.length,duplicates:duplicates.length,classification:classification.length,epistemic:epistemic.length,conflicts:conflicts.length,relations:relations.length,learning:learning.relations.length},relationSuggestionHealth:suggestionHealth(relations),learningHealth:learning.health,policy:{creatorDecisionRequired:true,autoEndpointResolution:false,autoCanonicalMerge:false,autoCurriculumOrder:false}};
}
export async function listReviewQueue(db,{queue='intake',limit=50}={}){const q=String(queue||'intake').toLowerCase();if(!REVIEW_QUEUES.has(q))throw Object.assign(new Error('unknown review queue'),{status:400,code:'UNKNOWN_REVIEW_QUEUE'});if(q==='intake')return{queue:q,items:await intakeQueue(db,limit)};if(q==='duplicates')return{queue:q,items:await duplicateQueue(db,limit)};if(q==='classification')return{queue:q,items:await classificationQueue(db,limit)};if(q==='epistemic')return{queue:q,items:await epistemicQueue(db,limit)};if(q==='conflicts')return{queue:q,items:await conflictQueue(db,limit)};if(q==='relations')return{queue:q,items:await relationQueue(db,limit)};const learning=await learningQueue(db,limit);return{queue:q,items:learning.relations,health:learning.health}}
async function extractionAction(db,{queue,id,action,payload,reviewer}){
 if(!UUID.test(id))throw Object.assign(new Error('valid extraction candidate id is required'),{status:400});
 if(action==='CHANGE'){
  const atomType=String(payload?.atomType||'').toUpperCase(),claimType=payload?.claimType?String(payload.claimType).toUpperCase():null;if(!ATOM_TYPES.has(atomType))throw Object.assign(new Error('valid atomType is required for CHANGE'),{status:400});if(claimType&&!CLAIM_TYPES.has(claimType))throw Object.assign(new Error('invalid claimType'),{status:400});
  const row=(await db.query(`UPDATE extraction_candidates SET atom_type=$2,claim_type=$3,metadata=metadata||$4::jsonb,updated_at=NOW() WHERE id=$1 AND review_status='PENDING' RETURNING id,atom_type,claim_type,candidate_text`,[id,atomType,claimType,JSON.stringify({creatorClassificationOverride:true})])).rows[0];if(!row)throw Object.assign(new Error('pending extraction candidate not found'),{status:404});await decision(db,{queueType:queue,subjectType:'EXTRACTION_CANDIDATE',subjectKey:id,action,payload:{atomType,claimType},reviewer});return row;
 }
 if(!['APPROVE','REJECT'].includes(action))throw Object.assign(new Error('action must be APPROVE, REJECT, or CHANGE'),{status:400});const status=action==='APPROVE'?'APPROVED':'REJECTED',row=(await db.query(`UPDATE extraction_candidates SET review_status=$2,reviewed_at=NOW(),reviewed_by=$3,updated_at=NOW() WHERE id=$1 AND review_status='PENDING' RETURNING id,review_status,candidate_text`,[id,status,reviewer])).rows[0];if(!row)throw Object.assign(new Error('pending extraction candidate not found'),{status:404});await decision(db,{queueType:queue,subjectType:'EXTRACTION_CANDIDATE',subjectKey:id,action,payload,reviewer});return row;
}
async function validateNode(db,nodeId){if(!NODE_KEY.test(String(nodeId||'')))return null;const{map}=await mapRecords(db);return map.nodes.find(node=>node.id===nodeId)||null}
async function relationAction(db,{queue,id,action,payload,reviewer}){
 if(!UUID.test(id))throw Object.assign(new Error('valid relation candidate id is required'),{status:400});
 if(action==='RESOLVE'){
  const current=(await db.query(`SELECT * FROM relation_candidates WHERE id=$1 AND review_status='PENDING'`,[id])).rows[0];if(!current)throw Object.assign(new Error('pending relation candidate not found'),{status:404});let from={nodeId:current.from_node_key,kind:current.from_kind,label:current.from_label,resolution:current.from_resolution},to={nodeId:current.to_node_key,kind:current.to_kind,label:current.to_label,resolution:current.to_resolution};
  if(payload?.fromNodeId){const node=await validateNode(db,payload.fromNodeId);if(!node)throw Object.assign(new Error('fromNodeId is not an observed Corpus Map node'),{status:400});from={nodeId:node.id,kind:node.kind,label:node.label,resolution:'MAPPED'}}
  if(payload?.toNodeId){const node=await validateNode(db,payload.toNodeId);if(!node)throw Object.assign(new Error('toNodeId is not an observed Corpus Map node'),{status:400});to={nodeId:node.id,kind:node.kind,label:node.label,resolution:'MAPPED'}}
  if(!ENDPOINT_KINDS.has(from.kind)||!ENDPOINT_KINDS.has(to.kind))throw Object.assign(new Error('invalid resolved endpoint kind'),{status:400});const endpoint=from.resolution==='MAPPED'&&to.resolution==='MAPPED'?'MAPPED':from.resolution==='MAPPED'||to.resolution==='MAPPED'?'PARTIAL':'UNRESOLVED';
  const row=(await db.query(`UPDATE relation_candidates SET from_node_key=$2,from_kind=$3,from_label=$4,from_resolution=$5,to_node_key=$6,to_kind=$7,to_label=$8,to_resolution=$9,endpoint_resolution=$10,metadata=metadata||$11::jsonb,updated_at=NOW() WHERE id=$1 AND review_status='PENDING' RETURNING id,endpoint_resolution,from_label,to_label`,[id,from.nodeId,from.kind,from.label,from.resolution,to.nodeId,to.kind,to.label,to.resolution,endpoint,JSON.stringify({creatorEndpointResolution:true})])).rows[0];await decision(db,{queueType:queue,subjectType:'RELATION_CANDIDATE',subjectKey:id,action,payload:{from,to,endpointResolution:endpoint},reviewer});return row;
 }
 if(!['APPROVE','REJECT'].includes(action))throw Object.assign(new Error('action must be APPROVE, REJECT, or RESOLVE'),{status:400});const current=(await db.query(`SELECT endpoint_resolution FROM relation_candidates WHERE id=$1 AND review_status='PENDING'`,[id])).rows[0];if(!current)throw Object.assign(new Error('pending relation candidate not found'),{status:404});if(action==='APPROVE'&&current.endpoint_resolution!=='MAPPED')throw Object.assign(new Error('resolve both relation endpoints before approval'),{status:409,code:'RELATION_ENDPOINTS_UNRESOLVED'});const status=action==='APPROVE'?'APPROVED':'REJECTED',row=(await db.query(`UPDATE relation_candidates SET review_status=$2,reviewed_at=NOW(),reviewed_by=$3,updated_at=NOW() WHERE id=$1 AND review_status='PENDING' RETURNING id,review_status,relation_type,from_label,to_label`,[id,status,reviewer])).rows[0];await decision(db,{queueType:queue,subjectType:'RELATION_CANDIDATE',subjectKey:id,action,payload,reviewer});return row;
}
export async function applyReviewDecision(db,{queue,id,subjectKey,action,payload={},reviewer}){const q=String(queue||'').toLowerCase(),a=String(action||'').toUpperCase();if(!REVIEW_QUEUES.has(q))throw Object.assign(new Error('unknown review queue'),{status:400});if(!reviewer)throw Object.assign(new Error('reviewer is required'),{status:400});if(q==='duplicates'){if(!['MERGE','KEEP_SEPARATE'].includes(a))throw Object.assign(new Error('duplicate action must be MERGE or KEEP_SEPARATE'),{status:400});if(!subjectKey)throw Object.assign(new Error('duplicate subjectKey is required'),{status:400});return decision(db,{queueType:'DUPLICATE',subjectType:'CONCEPT_CLUSTER',subjectKey,action:a,payload,reviewer})}if(['classification','epistemic'].includes(q))return extractionAction(db,{queue:q==='classification'?'CLASSIFICATION':'EPISTEMIC',id,action:a,payload,reviewer});if(q==='conflicts'){if(payload?.kind==='RELATION')return relationAction(db,{queue:'CONFLICT',id,action:a,payload,reviewer});return extractionAction(db,{queue:'CONFLICT',id,action:a,payload,reviewer})}if(['relations','learning'].includes(q))return relationAction(db,{queue:q==='learning'?'LEARNING_ORDER':'RELATION_ENDPOINT',id,action:a,payload,reviewer});throw Object.assign(new Error('intake decisions use the intake review endpoint'),{status:400,code:'USE_INTAKE_ACTION'})}
