import{semanticCapability,semanticMatcher}from'../matching/semantic-matcher.js';
import{multimodalCapability,describeImageForKnowledgeIntake}from'../intake/ai-gateway-multimodal.service.js';
import{getSourcePublicationHealth}from'../publication/source-publication.service.js';
import{getPublicationPlacementCatalog}from'../publication/flexible-publication.service.js';
import{previewLearningDependencyGraph}from'../learning/learning-dependency.service.js';

async function scalar(db,sql,params=[]){return Number((await db.query(sql,params)).rows[0]?.value||0)}
const PROBE_PNG=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZCWQAAAAASUVORK5CYII=','base64');
const safeGatewayError=error=>String(error?.gatewayError||error?.message||'').replace(/Bearer\s+\S+/gi,'Bearer [redacted]').replace(/[A-Za-z0-9_-]{80,}/g,'[redacted]').slice(0,240)||null;
const probeFailure=(error,fallbackCode)=>({attempted:true,ok:false,errorCode:String(error?.code||fallbackCode),gatewayStatus:Number(error?.gatewayStatus)||null,gatewayError:safeGatewayError(error)});

export async function backendCompletionHealth(db,{probeSemantic=false,probeVision=false}={}){
 const semantic=semanticCapability(),multimodal=multimodalCapability(),migration010=await scalar(db,`SELECT COUNT(*) AS value FROM schema_migrations WHERE name='database/migrations/010_backend_completion.sql'`),migration011=await scalar(db,`SELECT COUNT(*) AS value FROM schema_migrations WHERE name='database/migrations/011_learning_unit_titles.sql'`),migration012=await scalar(db,`SELECT COUNT(*) AS value FROM schema_migrations WHERE name='database/migrations/012_legacy_review_boundary.sql'`),columns=await db.query(`SELECT to_regclass('public.source_publications') IS NOT NULL AS publications,to_regclass('public.knowledge_reviews') IS NOT NULL AS legacy_reviews,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='source_publications' AND column_name='target_learning_unit_key') AS source_unit_key,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='source_publications' AND column_name='target_learning_unit_title') AS source_unit_title,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='published_learning_cards' AND column_name='learning_unit_key') AS card_unit_key,EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='published_learning_cards' AND column_name='learning_unit_title') AS card_unit_title`),publication=await getSourcePublicationHealth(db),catalog=await getPublicationPlacementCatalog(db),learning=await previewLearningDependencyGraph(db,{unitLimit:500,spiralLimit:500,dependencyLimit:1000}),relations=(await db.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE review_status='PENDING')::int AS pending,COUNT(*) FILTER(WHERE review_status='APPROVED')::int AS approved,COUNT(*) FILTER(WHERE endpoint_resolution='MAPPED')::int AS mapped FROM relation_candidates`)).rows[0];
 let semanticProbe={attempted:false,ok:null},visionProbe={attempted:false,ok:null};
 if(probeSemantic&&semantic.available){
  try{const result=await semanticMatcher.rank('נוירופלסטיות',[{id:'probe',text:'יכולת המוח להשתנות וליצור קשרים עצביים חדשים'}],{topK:1});semanticProbe={attempted:true,ok:Boolean(result.matches[0]&&Number.isFinite(result.matches[0].score)),score:result.matches[0]?.score??null,model:result.model}}
  catch(error){semanticProbe=probeFailure(error,'SEMANTIC_PROBE_FAILED')}
 }
 if(probeVision&&multimodal.available){
  try{const result=await describeImageForKnowledgeIntake({bytes:PROBE_PNG,mimeType:'image/png',fileName:'backend-health-probe.png'});visionProbe={attempted:true,ok:Boolean(result.text),model:result.model,textCharacters:String(result.text||'').length}}
  catch(error){visionProbe=probeFailure(error,'VISION_PROBE_FAILED')}
 }
 const schema=columns.rows[0]||{};
 const coreChecks={migration010:migration010===1,migration011:migration011===1,migration012:migration012===1,reviewBoundarySchema:Boolean(schema.legacy_reviews),flexiblePublicationColumns:Boolean(schema.publications&&schema.source_unit_key&&schema.source_unit_title&&schema.card_unit_key&&schema.card_unit_title),publicationIntegrity:Boolean(publication.ok),dynamicLearningUnits:Array.isArray(catalog.learningUnits)&&catalog.policy?.fixedChapterCount===false,learningGraphSafe:Number(learning.summary?.strictCycles||0)===0&&learning.method?.sourceOrderUsed===false&&learning.method?.fixedChapterCount===false,semanticConfigured:semantic.available,multimodalConfigured:multimodal.available};
 const probeChecks={semanticProbe:probeSemantic?semanticProbe.ok===true:null,visionProbe:probeVision?visionProbe.ok===true:null};
 const coreReady=Object.values(coreChecks).every(Boolean),requestedProbesPassed=(!probeSemantic||probeChecks.semanticProbe===true)&&(!probeVision||probeChecks.visionProbe===true),ok=coreReady&&requestedProbesPassed;
 return{ok,version:'backend-completion-v1.6',checks:{...coreChecks,...probeChecks},probes:{semantic:{requested:probeSemantic,attempted:semanticProbe.attempted,passed:probeChecks.semanticProbe},vision:{requested:probeVision,attempted:visionProbe.attempted,passed:probeChecks.visionProbe},notRequestedValue:null,requestedProbesIncludedInOk:true},semantic:{...semantic,probe:semanticProbe},multimodal:{...multimodal,probe:visionProbe},publication:{healthScope:'LEGACY_COMPATIBILITY_SERVICE',health:publication,effectivePolicy:{fixedChapterCount:false,dynamicLearningUnitKeys:true,dynamicLearningUnitTitles:true,legacyChapterAliasesSupported:true,creatorDecisionRequired:true,previewRequired:true,autoPlacement:false,autoPublish:false},placementCatalog:{learningUnits:catalog.learningUnits.length,policy:catalog.policy}},relations:{total:Number(relations.total||0),pending:Number(relations.pending||0),approved:Number(relations.approved||0),mapped:Number(relations.mapped||0),creatorReviewBoundary:true,semanticResolutionEndpointAvailable:true},learning:{units:Number(learning.summary?.learningUnits||learning.learningUnits?.length||0),strictCycles:Number(learning.summary?.strictCycles||0),fixedChapterCount:Boolean(learning.method?.fixedChapterCount),sourceOrderUsed:Boolean(learning.method?.sourceOrderUsed)},policy:{backendReadyBeforeVisualRedesign:coreReady,creatorApprovalRemainsRequired:true,aiNeverWritesCanonicalTruth:true,dynamicLearningUnitTitles:true,configuredDoesNotImplyProbePassed:true,reviewRoutesFailClosed:true,legacyReviewSchemaMigrationOwned:true,relationReviewMayRemainPendingWithoutBlockingBackendReadiness:true}};
}
