import React,{useEffect,useMemo,useState}from'react';

type Evidence={chapter:number;sourceFile:string;paragraph:number;text:string};
type Insight={id:string;title:string;topic:string;chapters:number[];confidence:string;evidence:Evidence[];traceable:boolean};
type Action={id:string;title:string;why:string;done:boolean;createdAt:string};
type Reflection={id:string;text:string;createdAt:string};
type Props={page:string;onNav:(id:string)=>void};

const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const save=(key:string,value:any)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};

export default function EvolutionWorkspace({page,onNav}:Props){
 const[insights,setInsights]=useState<Insight[]>([]),[loading,setLoading]=useState(false),[focus,setFocus]=useState<Insight|null>(()=>read<Insight|null>('eil-focus',null));
 const[actions,setActions]=useState<Action[]>(()=>read<Action[]>('eil-actions',[])),[reflections,setReflections]=useState<Reflection[]>(()=>read<Reflection[]>('eil-reflections',[]));
 const[actionText,setActionText]=useState(''),[reflectionText,setReflectionText]=useState(''),[question,setQuestion]=useState(''),[mentor,setMentor]=useState<any>(null),[asking,setAsking]=useState(false);
 useEffect(()=>{if(!insights.length){setLoading(true);fetch('/api/insights').then(r=>r.json()).then(d=>{if(d.ok)setInsights(d.insights||[])}).catch(()=>{}).finally(()=>setLoading(false))}},[]);
 useEffect(()=>save('eil-actions',actions),[actions]);useEffect(()=>save('eil-reflections',reflections),[reflections]);useEffect(()=>save('eil-focus',focus),[focus]);
 const active=useMemo(()=>actions.filter(a=>!a.done),[actions]);
 const choose=(i:Insight)=>{setFocus(i);onNav('journey')};
 const addAction=()=>{const title=actionText.trim();if(!title)return;setActions(x=>[{id:crypto.randomUUID(),title,why:focus?.topic||'בחירה אישית',done:false,createdAt:new Date().toISOString()},...x]);setActionText('')};
 const addReflection=()=>{const text=reflectionText.trim();if(!text)return;setReflections(x=>[{id:crypto.randomUUID(),text,createdAt:new Date().toISOString()},...x]);setReflectionText('')};
 const ask=async()=>{if(!question.trim())return;setAsking(true);setMentor(null);try{const r=await fetch('/api/mentor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});setMentor(await r.json())}finally{setAsking(false)}};
 const Header=({kicker,title,sub}:{kicker:string;title:string;sub:string})=><header className="evoPageHead"><span>{kicker}</span><h1>{title}</h1><p>{sub}</p></header>;
 if(page==='insights')return <div className="evoWorkspace"><Header kicker="SEE THE PATTERN" title="תובנות" sub="לא עוד רשימת רעיונות. כאן מחפשים דברים שחוזרים בין מקורות שונים ושווים תשומת לב."/><div className="evoSplit"><section className="evoPrimary"><div className="evoSectionTitle"><b>דפוסים שחוצים מקורות</b><small>{loading?'מנתח...':`${insights.length} קשרים זמינים`}</small></div>{insights.map(i=><article className={'insightCard '+(focus?.id===i.id?'selected':'')} key={i.id}><div className="insightTop"><span>{i.topic}</span><em>{i.chapters.length} פרקים</em></div><h3>{i.title}</h3><p>{i.evidence[0]?.text||'הקשר קיים במפת הידע וממתין לעדות נוספת.'}</p><div className="evidenceLine">{i.chapters.slice(0,6).map(n=><i key={n}>#{n}</i>)}</div><button onClick={()=>choose(i)}>שים במודעות →</button></article>)}</section><aside className="evoAside"><span className="miniLabel">AWARENESS FILTER</span><h3>תובנה טובה לא מסתיימת ב״מעניין״.</h3><p>בחר דפוס אחד. הוא יהפוך לפוקוס במסע האישי ויקבל פעולה שאפשר לבדוק בעולם האמיתי.</p>{focus&&<div className="focusMini"><small>הפוקוס הנוכחי</small><b>{focus.topic}</b><button onClick={()=>onNav('journey')}>פתח</button></div>}</aside></div></div>;
 if(page==='journey')return <div className="evoWorkspace"><Header kicker="AWARENESS → CHOICE → ACTION" title="המסע שלי" sub="המקום שבו ידע מפסיק להיות משהו שקראת והופך למשהו שאתה בודק בחיים."/><section className="journeyFocus">{focus?<><div><span className="miniLabel">מה נמצא כרגע בפרונט</span><h2>{focus.topic}</h2><p>{focus.evidence[0]?.text||focus.title}</p><div className="focusSources">מבוסס על פרקים {focus.chapters.join(' · ')}</div></div><button className="textEvoBtn" onClick={()=>onNav('insights')}>החלף פוקוס</button></>:<><div><span className="miniLabel">אין פוקוס פעיל</span><h2>בחר דבר אחד שראוי למודעות שלך.</h2><p>תובנות הופכות שימושיות רק כשאחת מהן מקבלת קדימות.</p></div><button className="primary" onClick={()=>onNav('insights')}>בחר מתוך התובנות</button></>}</section><div className="evolutionRail"><div className="railStep done"><i>01</i><b>מודעות</b><span>{focus?'דפוס נבחר':'ממתין לבחירה'}</span></div><div className={'railStep '+(focus?'done':'')}><i>02</i><b>בחירה</b><span>מה אני רוצה לשנות?</span></div><div className={'railStep '+(active.length?'done':'')}><i>03</i><b>פעולה</b><span>{active.length?`${active.length} ניסויים פעילים`:'עדיין אין ניסוי'}</span></div><div className={'railStep '+(reflections.length?'done':'')}><i>04</i><b>התבוננות</b><span>{reflections.length?'יש למידה מהשטח':'עוד לא חזר מידע'}</span></div></div><section className="evoActionComposer"><span className="miniLabel">TURN KNOWING INTO LIVING</span><h3>מה פעולה קטנה שתיתן לנו מידע אמיתי?</h3><div><input value={actionText} onChange={e=>setActionText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addAction()} placeholder="לדוגמה: במשך 5 ימים לעצור לפני תגובה ולתת שם לרגש..."/><button className="primary" onClick={addAction}>צור ניסוי</button></div></section><section className="activeExperiments"><div className="evoSectionTitle"><b>ניסויים פעילים</b><button onClick={()=>onNav('tasks')}>כל הפעולות</button></div>{active.length?active.map(a=><label className="experiment" key={a.id}><input type="checkbox" checked={a.done} onChange={()=>setActions(x=>x.map(v=>v.id===a.id?{...v,done:!v.done}:v))}/><div><b>{a.title}</b><small>נולד מתוך: {a.why}</small></div></label>):<div className="evoEmpty">אין עדיין ניסוי פעיל. המטרה היא לא משימה גדולה — אלא פעולה קטנה שאפשר ללמוד ממנה.</div>}</section></div>;
 if(page==='tasks')return <div className="evoWorkspace"><Header kicker="EXPERIMENTS, NOT TO-DOS" title="פעולות" sub="לא רשימת מטלות. אלה ניסויים שנועדו לבדוק אם הבנה חדשה משנה משהו בעולם האמיתי."/><section className="experimentList">{actions.map(a=><article className={a.done?'isDone':''} key={a.id}><button className="checkCircle" onClick={()=>setActions(x=>x.map(v=>v.id===a.id?{...v,done:!v.done}:v))}>{a.done?'✓':''}</button><div><h3>{a.title}</h3><p>למה: {a.why}</p></div><span>{a.done?'נבדק':'פעיל'}</span></article>)}{!actions.length&&<div className="evoEmpty">עוד אין פעולות. בחר תובנה במסע והפוך אותה לניסוי.</div>}</section><button className="primary" onClick={()=>onNav('journey')}>חזרה למסע</button></div>;
 if(page==='journal')return <div className="evoWorkspace"><Header kicker="REFLECT" title="התבוננות" sub="השלב שבו העולם מחזיר מידע: מה קרה כשניסית לחיות משהו שהבנת?"/><section className="reflectionComposer"><textarea value={reflectionText} onChange={e=>setReflectionText(e.target.value)} placeholder="מה שמתי לב אליו? מה השתנה? מה הפתיע אותי?"/><button className="primary" onClick={addReflection}>שמור התבוננות</button></section><section className="reflectionFeed">{reflections.map(r=><article key={r.id}><time>{new Date(r.createdAt).toLocaleDateString('he-IL')}</time><p>{r.text}</p></article>)}{!reflections.length&&<div className="evoEmpty">עוד אין התבוננויות. אחרי ניסוי קטן, חזור לכאן ותכתוב מה באמת קרה.</div>}</section></div>;
 if(page==='mentor')return <div className="evoWorkspace"><Header kicker="SOURCE-GROUNDED THINKING" title="המנטור" sub="שאלה אחת, מול כל מה שכבר צברת. קודם מקור, אחר כך פרשנות."/><section className="mentorBox"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="מה אני רוצה להבין מתוך הידע שלי?"/><button className="primary" onClick={ask} disabled={asking}>{asking?'מחפש במקורות...':'שאל את E.I.L'}</button></section>{mentor&&<section className="mentorAnswer"><span className="miniLabel">SOURCE FIRST</span><h3>{mentor.answer}</h3>{mentor.evidence?.map((e:Evidence,i:number)=><blockquote key={i}><p>{e.text}</p><footer>פרק {e.chapter} · {e.sourceFile} · פסקה {e.paragraph}</footer></blockquote>)}</section>}</div>;
 return null;
}
