import React from 'react';

type Page={id:string;label:string;icon:string};
type Group={title:string;items:string[][]};
type Props={page:string;groups:Group[];onNav:(id:string)=>void;onAdd:()=>void;collapsed:boolean;setCollapsed:(v:boolean)=>void;online:boolean};

export function Sidebar({page,groups,onNav,onAdd,collapsed,setCollapsed,online}:Props){return <aside className={'sideRail '+(collapsed?'collapsed':'')}>
  <div className="sideBrand"><button className="brandMark" onClick={()=>onNav('dashboard')}>E</button>{!collapsed&&<div><b>E.I.L</b><small>EVOLUTION OS</small></div>}<button className="collapseBtn" onClick={()=>setCollapsed(!collapsed)}>{collapsed?'‹':'›'}</button></div>
  <button className="sideAdd" onClick={onAdd}><span>＋</span>{!collapsed&&'הוסף מקור'}</button>
  <nav className="sideNav"><button className={page==='dashboard'?'sideLink active':'sideLink'} onClick={()=>onNav('dashboard')}><i>⌂</i>{!collapsed&&<><span>היום</span><em>נקודת המודעות</em></>}</button>
  {groups.map(g=><section className="sideGroup" key={g.title}>{!collapsed&&<label>{g.title}</label>}{g.items.map(([id,label,icon])=><button className={page===id?'sideLink active':'sideLink'} key={id} onClick={()=>onNav(id)} title={label}><i>{icon}</i>{!collapsed&&<span>{label}</span>}</button>)}</section>)}</nav>
  <div className="sideFooter"><span className={online?'pulse online':'pulse'}/>{!collapsed&&<div><b>{online?'המערכת מחוברת':'מצב מקומי'}</b><small>הידע נשאר מקור. ההבנה מתפתחת.</small></div>}</div>
</aside>}

type DashProps={onNav:(id:string)=>void;onAdd:()=>void;itemsCount:number;paragraphs:number;corpusReady:boolean};
const local=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
export function EvolutionDashboard({onNav,onAdd,itemsCount,paragraphs,corpusReady}:DashProps){
 const focus=local<any>('eil-focus',null),actions=local<any[]>('eil-actions',[]),reflections=local<any[]>('eil-reflections',[]),active=actions.filter(a=>!a.done),latestReflection=reflections[0];
 const hasFocus=!!focus,hasAction=active.length>0,hasReflection=!!latestReflection;
 const nextLabel=!hasFocus?'בחר פוקוס אחד':!hasAction?'הפוך הבנה לניסוי':!hasReflection?'חזור עם מה שקרה':'סגור לולאה והעמק';
 const nextTarget=!hasFocus?'insights':!hasAction?'journey':!hasReflection?'journal':'journey';
 return <div className="evolutionDash">
 <header className="dashIntro"><div><span className="eyebrow">E.I.L / AWARENESS → ACTION</span><h1>מה נמצא בפרונט עכשיו?</h1><p>המערכת לא מודדת כמה ידע צברת. היא מחזיקה עבורך את החוט שבין מה שכבר למדת, מה שאתה רואה עכשיו, ומה כדאי לבדוק בחיים עצמם.</p></div><button className="quietAdd" onClick={onAdd}>＋ הוסף משהו שלמדתי</button></header>
 <section className="awarenessHero"><div className="awarenessCopy"><span className="heroKicker">YOUR CURRENT EDGE</span><h2>{hasFocus?focus.topic:'עדיין אין פוקוס פעיל.'}</h2><p>{hasFocus?(focus.evidence?.[0]?.text||focus.title):'בחר דפוס אחד מתוך הידע שלך והצב אותו במרכז. משם E.I.L יוביל אותך להבין, לנסות ולהתבונן — לא לצבור עוד מידע.'}</p><div className="heroActions"><button className="primary" onClick={()=>onNav(hasFocus?'journey':'insights')}>{hasFocus?'פתח את המסע':'בחר פוקוס'}</button><button className="ghostAction" onClick={()=>onNav('insights')}>ראה תובנות</button></div></div><div className="awarenessLoop"><div className="loopCore"><small>עכשיו</small><b>מודעות</b><span>{hasFocus?focus.topic:'בחר דפוס'}</span></div><i className={'loopNode n1 '+(hasFocus?'lit':'')}>לקלוט<small>מקור</small></i><i className={'loopNode n2 '+(hasFocus?'lit':'')}>לחבר<small>דפוס</small></i><i className={'loopNode n3 '+(hasAction?'lit':'')}>לפעול<small>ניסוי</small></i><i className={'loopNode n4 '+(hasReflection?'lit':'')}>להתבונן<small>למידה</small></i></div></section>
 <section className="liveStateGrid"><article className={'liveStateCard '+(hasFocus?'active':'')} onClick={()=>onNav(hasFocus?'journey':'insights')}><span>01 / מודעות</span><h3>{hasFocus?focus.topic:'מה דורש תשומת לב?'}</h3><p>{hasFocus?`מחובר לפרקים ${focus.chapters?.join(' · ')||''}`:'בחר תובנה אחת והפוך אותה לפוקוס.'}</p><b>{hasFocus?'בפרונט':'ממתין לבחירה'} →</b></article><article className={'liveStateCard '+(hasAction?'active':'')} onClick={()=>onNav(hasAction?'tasks':'journey')}><span>02 / פעולה</span><h3>{hasAction?active[0].title:'מה אני בודק במציאות?'}</h3><p>{hasAction?`נולד מתוך: ${active[0].why}`:'הפוך את ההבנה לפעולה קטנה שאפשר ללמוד ממנה.'}</p><b>{hasAction?`${active.length} ניסויים פעילים`:'צור ניסוי'} →</b></article><article className={'liveStateCard '+(hasReflection?'active':'')} onClick={()=>onNav('journal')}><span>03 / התבוננות</span><h3>{hasReflection?'מה למדתי מהשטח?':'מה קרה כשניסיתי?'}</h3><p>{hasReflection?latestReflection.text:'חזור אחרי פעולה וכתוב מה באמת השתנה, הפתיע או התנגד.'}</p><b>{hasReflection?'פתח התבוננות':'כתוב התבוננות'} →</b></article></section>
 <section className="nextMove liveNext"><div><span className="cardLabel">NEXT MOVE</span><h3>{nextLabel}</h3><p>{!hasFocus?'לא צריך עוד חומר. צריך לבחור למה לתת תשומת לב.':!hasAction?'הבנה בלי ניסוי נשארת רעיון.':!hasReflection?'הפעולה כבר קיימת; עכשיו צריך מידע מהחיים עצמם.':'יש לך לולאה מלאה. עכשיו אפשר לבחור מה השתנה ומה ראוי לסיבוב הבא.'}</p></div><button className="primary" onClick={()=>onNav(nextTarget)}>המשך מכאן ←</button></section>
 <section className="signalStrip quietSignals"><button onClick={()=>onNav('library')}><strong>18</strong><span>תחנות במסע</span><small>שכבות של הבנה</small></button><button onClick={()=>onNav('sources')}><strong>{paragraphs||'—'}</strong><span>פסקאות מקור</span><small>{corpusReady?'המקור המלא מחובר':'המקור נטען'}</small></button><button onClick={()=>onNav('insights')}><strong>{hasFocus?'1':'0'}</strong><span>פוקוס פעיל</span><small>מה נמצא בפרונט</small></button><button onClick={()=>onNav('tasks')}><strong>{active.length}</strong><span>ניסויים פעילים</span><small>מה נבדק עכשיו</small></button></section>
 </div>}
