import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{chapters}from'./data/chapters';
import{chaptersFull}from'./data/chapters-full';
import'./styles.css';

type Item={id?:number;title:string;kind:string;content?:string;tags?:string[];source?:string};type Page={id:string;label:string;icon:string};
const groups=[{title:'KNOWLEDGE',items:[['library','הספרייה','▦'],['inbox','Inbox','↓'],['atlas','Atlas','◉'],['topics','נושאים','◇'],['sources','מקורות','↗'],['files','קבצים','□']]},{title:'THINK',items:[['mentor','המנטור','✦'],['research','מחקר','⌕'],['insights','תובנות','✧']]},{title:'PERSONAL',items:[['journal','היומן','✎'],['journey','המסע שלי','↗'],['notes','הערות','≡'],['collections','אוספים','▤']]},{title:'SYSTEM',items:[['tasks','משימות','✓'],['activity','פעילות','◷'],['profile','פרופיל','○'],['settings','הגדרות','⚙']]}];
const pages:Page[]=[{id:'dashboard',label:'לוח בקרה',icon:'⌂'},...groups.flatMap(g=>g.items.map(([id,label,icon])=>({id,label,icon} as Page)))];
const clean=(s:string)=>s.replace(/^פרק \d+:\s*/,'');const localItems=():Item[]=>{try{return JSON.parse(localStorage.getItem('eil-items')||'[]')}catch{return[]}};
function App(){const[page,setPage]=useState('dashboard');const[items,setItems]=useState<Item[]>(localItems);const[q,setQ]=useState('');const[chapter,setChapter]=useState(1);const[menu,setMenu]=useState(false);const[editor,setEditor]=useState(false);const[form,setForm]=useState<Item>({title:'',kind:'ידע',content:'',source:'',tags:[]});const[busy,setBusy]=useState(false);const[online,setOnline]=useState(false);const[notice,setNotice]=useState('');
useEffect(()=>{fetch('/api/items').then(r=>r.ok?r.json():Promise.reject()).then(d=>{setItems(d.items||[]);setOnline(true)}).catch(()=>setOnline(false))},[]);
const filtered=useMemo(()=>items.filter(i=>(i.title+' '+(i.content||'')+' '+(i.source||'')+' '+(i.tags||[]).join(' ')).toLowerCase().includes(q.toLowerCase())),[items,q]);
const openNew=()=>{setForm({title:'',kind:'ידע',content:'',source:'',tags:[]});setEditor(true)};const save=async()=>{if(!form.title.trim())return;setBusy(true);try{const r=await fetch('/api/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw Error();const d=await r.json();setItems(x=>[d.item,...x]);setOnline(true);setNotice('הידע נשמר ב־E.I.L')}catch{const x={...form,id:Date.now()};const next=[x,...items];setItems(next);localStorage.setItem('eil-items',JSON.stringify(next));setNotice('נשמר מקומית — ה־API אינו זמין')}finally{setBusy(false);setEditor(false)}};
const nav=(id:string)=>{setPage(id);setMenu(false)};const current=pages.find(p=>p.id===page)||pages[0];
const Header=({title,sub}:{title:string;sub:string})=><div className="pageTitle"><div><span className="eyebrow">E.I.L / KNOWLEDGE OS</span><h1>{title}</h1><p>{sub}</p></div><button className="primary" onClick={openNew}>+ הוסף ידע</button></div>;
const ItemRow=({i}:{i:Item})=><div className="item"><span>●</span><div><strong>{i.title}</strong><small>{i.kind}{i.tags?.length?' · '+i.tags.join(' · '):''}</small></div></div>;
const Dashboard=()=><><Header title="ברוך הבא ל־E.I.L 👋" sub="Everything I Learned — מרחב אחד שבו הידע שלך מתחבר, מתפתח והופך לפעולה."/><section className="hero"><div><span className="eyebrow">YOUR KNOWLEDGE OS</span><h2>כל מה שלמדת,<br/>מתחיל להתחבר.</h2><p>הספרייה, 18 פרקי הבסיס, המחקר, התובנות והמסע שלך — במרחב אחד.</p><button className="primary" onClick={openNew}>+ הוסף משהו שלמדתי</button></div><div className="heroGraph"><i>זהות</i><i>מוח</i><i>רגשות</i><i>פעולה</i><i>ידע</i></div></section><section className="stats"><article className="stat" onClick={()=>nav('library')}><span>▦</span><div><b>{items.length}</b><strong>הספרייה</strong><small>פריטי ידע</small></div></article><article className="stat" onClick={()=>nav('library')}><span>◈</span><div><b>18</b><strong>פרקי בסיס</strong><small>תוכן ממופה</small></div></article><article className="stat" onClick={()=>nav('atlas')}><span>◉</span><div><b>5</b><strong>Atlas</strong><small>קטגוריות־על</small></div></article><article className="stat" onClick={()=>nav('insights')}><span>✧</span><div><b>12</b><strong>תובנות</strong><small>מקום לבנות ממנו</small></div></article></section><section className="panel"><div className="toolbar"><h2>ידע אחרון</h2><button className="secondary" onClick={()=>nav('library')}>הכול</button></div>{filtered.slice(0,6).map((i,k)=><ItemRow key={i.id||k} i={i}/>)}{!items.length&&<div className="empty">הוסף את פריט הידע הראשון שלך.</div>}</section></>;
const Library=()=>{const full=chaptersFull.length?chaptersFull:chapters;const selected=full[chapter-1] as any;return <><Header title="הספרייה" sub="18 פרקי הבסיס + הידע האישי שלך."/><section className="panel"><div className="toolbar"><h2>18 פרקי הבסיס</h2><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חפש בכל הידע..."/></div>{full.map((c:any)=><button className="chapterLink" key={c.number} onClick={()=>setChapter(c.number)}><span>{String(c.number).padStart(2,'0')}</span><div><strong>{clean(c.title)}</strong><small>{c.subtitle}</small></div><b>›</b></button>)}</section><section className="panel readerPanel"><div className="chapterMeta"><span>CHAPTER {String(selected.number).padStart(2,'0')} · {selected.sourceFile}</span><span>{selected.number}/18</span></div><h2>{clean(selected.title)}</h2><p className="lead">{selected.subtitle}</p><div className="progress"><i style={{width:`${selected.number/18*100}%`}}/></div><article className="content">{selected.paragraphs.map((p:string,i:number)=><p key={i}>{p}</p>)}</article><div className="chapterNav"><button className="secondary" disabled={selected.number===1} onClick={()=>setChapter(Math.max(1,selected.number-1))}>← הקודם</button><button className="primary" disabled={selected.number===18} onClick={()=>setChapter(Math.min(18,selected.number+1))}>הבא →</button></div></section><section className="panel"><div className="toolbar"><h2>הידע האישי שלך</h2><button className="secondary" onClick={openNew}>+ חדש</button></div>{filtered.map((i,k)=><ItemRow key={i.id||k} i={i}/>)}{!filtered.length&&<div className="empty">אין עדיין פריטי ידע אישיים.</div>}</section></>};
const Generic=({p}:{p:Page})=><><Header title={p.label} sub={`מרחב ${p.label} של E.I.L.`}/><div className="genericGrid"><section className="panel"><h2>התחל כאן</h2><textarea className="bigInput" placeholder="כתוב כאן..."/><button className="primary">שמור</button></section><section className="panel"><span className="eyebrow">SYSTEM</span><h2>{online?'API מחובר':'מצב מקומי'}</h2><p>המודול נמצא בתוך ה־workspace.</p></section></div></>;
return <div className="app"><button className="menuButton" onClick={()=>setMenu(true)}>☰<span>E.I.L</span></button>{menu&&<div className="drawerBackdrop" onClick={()=>setMenu(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerBrand"><strong>E.I.L</strong><button onClick={()=>setMenu(false)}>×</button></div><button className={page==='dashboard'?'drawerItem active':'drawerItem'} onClick={()=>nav('dashboard')}>⌂ לוח בקרה</button>{groups.map(g=><div className="drawerGroup" key={g.title}><span>{g.title}</span>{g.items.map(([id,label,icon])=><button className={page===id?'drawerItem active':'drawerItem'} key={id} onClick={()=>nav(id)}><b>{icon}</b>{label}</button>)}</div>)}<small className="drawerStatus">{online?'● API מחובר':'○ מצב מקומי'} · React / Node / PostgreSQL</small></aside></div>}<main><div className="topbar"><div className="globalSearch">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="חפש בכל E.I.L..."/></div></div>{notice&&<div className="notice" onClick={()=>setNotice('')}>{notice}</div>}{page==='dashboard'&&<Dashboard/>}{page==='library'&&<Library/>}{page!=='dashboard'&&page!=='library'&&<Generic p={current}/>} {editor&&<div className="overlay" onClick={()=>setEditor(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modalHead"><div><span className="eyebrow">ADD KNOWLEDGE</span><h2>הוסף ידע ל־E.I.L</h2></div><button className="close" onClick={()=>setEditor(false)}>×</button></div><label>כותרת<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>סוג<input value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}/></label><label>תוכן<textarea rows={8} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><label>מקור<input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><div className="actions"><button className="secondary" onClick={()=>setEditor(false)}>ביטול</button><button className="primary" disabled={busy} onClick={save}>{busy?'שומר...':'שמור ב־E.I.L'}</button></div></div></div>}</main></div>}
createRoot(document.getElementById('root')!).render(<App/>);