import React,{useState}from'react';
import'./opening.css';

type Props={onBegin:()=>void;onCreator:()=>void};
const questions=['מי אני?','מה אני?','למה אני כאן?','האם יש תכלית לקיום האנושי?','ומה אני עושה עם הזמן שיש לי?'];
export default function OpeningExperience({onBegin,onCreator}:Props){
 const[step,setStep]=useState(0),[answer,setAnswer]=useState('');
 const begin=()=>{if(answer.trim())localStorage.setItem('eil-origin-answer',answer.trim());localStorage.setItem('eil-access-mode','journey');localStorage.setItem('eil-journey-progress','1');localStorage.setItem('eil-intro-seen','1');onBegin()};
 return <div className="opening"><button className="creatorEntry" onClick={onCreator}>כניסת יוצר ↗</button><div className="openingMark">E.I.L</div>{step===0&&<section className="openingScene openingHero"><span>EVERYTHING STARTS WITH A QUESTION</span><h1>מי אני?</h1><p>לא ככותרת. לא כתשובה מוכנה.<br/>כשאלה שממנה התחיל מחקר של שנים.</p><button onClick={()=>setStep(1)}>להתחיל ←</button></section>}{step===1&&<section className="openingScene"><span>נקודת המוצא</span><h2>יצאתי למחקר.</h2><p className="openingText">המטרה שלו היא לנתח, להבין, לקשר ולהגיע למסקנות. יש עובדה אחת שקשה להתעלם ממנה: כל יצור נולד, חי ומת. ובין שתי הנקודות האלה נשארות שאלות.</p><div className="questionCloud">{questions.map((q,i)=><i key={q} style={{animationDelay:`${i*.12}s`}}>{q}</i>)}</div><button onClick={()=>setStep(2)}>אז מאיפה מתחילים? ←</button></section>}{step===2&&<section className="openingScene"><span>הבחנה ראשונה</span><h2>כדי להבין אדם,<br/>צריך קודם לפרק את המכלול.</h2><div className="humanModel"><div><small>המכלול</small><b>אדם</b></div><i>→</i><div><small>החלק הפיזי</small><b>גוף</b></div><span>＋</span><div><small>החלק המופשט</small><b>״מערכת הפעלה״</b></div></div><p className="openingText">נתחיל במה שאפשר לראות, למדוד ולחקור — ומשם נתקדם בהדרגה אל המוח, התודעה, הזהות, הרגש, המשמעות והתכלית.</p><button onClick={()=>setStep(3)}>לפני שיוצאים למסע ←</button></section>}{step===3&&<section className="openingScene openingQuestion"><span>שמור נקודת מוצא</span><h2>מי אתה?</h2><p>אין תשובה נכונה. כתוב את מה שנכון לך עכשיו. נחזור לאותה שאלה בהמשך ונראה מה השתנה.</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="אני..." autoFocus/><small>התשובה נשמרת אצלך ותהפוך לנקודת השוואה לאורך המסע.</small><button onClick={begin}>צא למסע ←</button></section>}<div className="openingDots">{[0,1,2,3].map(i=><i key={i} className={i===step?'on':''}/>)}</div></div>;
}
