import React,{useMemo,useState}from'react';
import{learningPath,stageLabels,worldLabels}from'./data/learning-path';

type Chapter={number:number;title:string;subtitle:string;sourceFile:string;paragraphs:string[];paragraphCount?:number;characterCount?:number};
type Props={chapters:Chapter[];query:string;setQuery:(v:string)=>void;corpusReady:boolean;paragraphs:number;characters:number};
const clean=(s:string)=>s.replace(/^פרק\s*\d+[:：]?\s*/,'');
const worlds=['SELF','BODY','MIND','SYSTEMS','MEANING'];
const short=(s:string)=>s.trim().length>0&&s.trim().length<55;
const looksHeading=(s:string,i:number,arr:string[])=>{const t=s.trim();if(!t)return false;if(/^פרק\s*\d+/u.test(t))return true;if(/^[\d]+\.\s+/u.test(t)&&t.length<90)return true;if(short(t)&&!/[.!?…]$/.test(t)&&i>2){const next=arr[i+1]?.trim()||'';return next.length>t.length||next.includes(':')}return false};
const looksQuote=(s:string)=>/^["“״]|["”״]\s*[-—]/u.test(s.trim());
const looksBullet=(s:string)=>/^[-•✓→]|^\d+[.)]\s/u.test(s.trim());

function StructuredSource({chapter}:{chapter:Chapter}){const blocks=chapter.paragraphs.map((text,i)=>({text,i,type:looksHeading(text,i,chapter.paragraphs)?'heading':looksQuote(text)?'quote':looksBullet(text)?'bullet':'paragraph'}));return <article className="learningSource">{blocks.map(b=>b.type==='heading'?<h3 key={b.i}>{b.text}</h3>:b.type==='quote'?<blockquote key={b.i}>{b.text}</blockquote>:b.type==='bullet'?<div className="sourceBullet" key={b.i}><span>•</span><p>{b.text.replace(/^[-•✓→]\s*/,'')}</p></div>:<p key={b.i}>{b.text}</p>)}</article>}

export default function SpiralLibrary({chapters,query,setQuery,corpusReady,paragraphs,characters}:Props){
 const[active,setActive]=useState<number|null>(null);const[mode,setMode]=useState<'owner'|'journey'>('owner');
 const[progress,setProgress]=useState(()=>{try{return Number(localStorage.getItem('eil-journey-progress')||1)}catch{return 1}});
 const filtered=useMemo(()=>{const n=query.trim().toLowerCase();if(!n)return chapters;return chapters.filter(c=>(c.title+' '+c.subtitle+' '+c.paragraphs.join(' ')).toLowerCase().includes(n))},[chapters,query]);
 const chapter=active?chapters.find(c=>c.number===active):null;const path=chapter?learningPath.find(x=>x.number===chapter.number):null;
 const accessible=(n:number)=>mode==='owner'||n<=progress;
 const open=(n:number)=>{if(accessible(n)){setActive(n);window.scrollTo({top:0,behavior:'smooth'})}};
 const complete=()=>{if(!chapter)return;const next=Math.min(18,Math.max(progress,chapter.number+1));setProgress(next);try{localStorage.setItem('eil-journey-progress',String(next))}catch{};if(chapter.number<18)setActive(chapter.number+1)};
 if(chapter&&path)return <div className="learningChapter"><div className="learningTop"><button className="textButton" onClick={()=>setActive(null)}>← חזרה למסע</button><div className="modeSwitch"><button className={mode==='owner'?'active':''} onClick={()=>setMode('owner')}>יוצר</button><button className={mode==='journey'?'active':''} onClick={()=>setMode('journey')}>מסע</button></div></div><section className="chapterCover"><div><span className="eyebrow">{worldLabels[path.world]} · {stageLabels[path.stage]}</span><h1>{clean(chapter.title)}</h1><p>{path.goal}</p><div className="chapterBadges"><span>{chapter.paragraphCount??chapter.paragraphs.length} פסקאות מקור</span><span>{path.accent}</span><span>פרק {chapter.number} מתוך 18</span></div></div><div className="chapterOrb"><b>{String(chapter.number).padStart(2,'0')}</b><small>{stageLabels[path.stage]}</small></div></section><section className="learningFlow"><article className="learningStep visual"><span>01 · לראות</span><h2>תמונה אחת לפני הפרטים</h2><p>כאן יופיע ויזואל שמציג את הרעיון המרכזי של הפרק לפני שנכנסים להסבר.</p><button disabled>ויזואל בפיתוח</button></article><article className="learningStep video"><span>02 · לחוות</span><h2>הסבר קצר. עד דקה.</h2><p>Micro‑lesson שייתן אינטואיציה לפני הטקסט העמוק.</p><button disabled>וידאו 30–60 שנ׳ · בפיתוח</button></article><article className="learningStep concept"><span>03 · להבין</span><h2>{chapter.subtitle||clean(chapter.title)}</h2><p>{path.goal}</p><div className="insightPrompt">💡 בזמן הלמידה E.I.L יחבר את הרעיון למה שכבר פגשת במסע.</div></article><article className="learningStep connect"><span>04 · לחבר</span><h2>מה נבנה על מה?</h2><p>{chapter.number===1?'זהו בסיס המסע. מכאן נתחיל לבנות שכבה על שכבה.':`הפרק הזה חוזר לרעיונות שכבר פגשנו ומוסיף שכבה חדשה מעל פרק ${chapter.number-1}.`}</p></article><article className="learningStep apply"><span>05 · ליישם</span><h2>עצירה קצרה</h2><p>מה מתוך הפרק הזה משנה משהו בדרך שבה אתה מסתכל על עצמך או על העולם?</p><textarea placeholder="כתוב תובנה אישית..."/></article></section><section className="sourceDivider"><div><span className="eyebrow">SOURCE OF TRUTH</span><h2>המקור המלא</h2><p>שכבת הלמידה מעל המסמך. הטקסט המקורי נשאר נגיש בשלמותו.</p></div><span className="sourcePill">SOURCE · FULL</span></section><StructuredSource chapter={chapter}/><div className="journeyComplete"><div><b>{chapter.number===18?'המסע הושלם':'מוכן לשכבה הבאה?'}</b><p>{chapter.number===18?'חזרת לשאלה הראשונה עם 17 שכבות חדשות של הבנה.':'סיום הפרק פותח את התחנה הבאה במצב מסע.'}</p></div>{chapter.number<18&&<button className="primary" onClick={complete}>סיימתי · המשך לפרק {chapter.number+1}</button>}</div></div>;
 return <div className="journeyLibrary"><div className="journeyHeader"><div><span className="eyebrow">E.I.L / SPIRAL LEARNING</span><h1>מסע הידע</h1><p>לא רשימת מסמכים — מסלול שבו כל רעיון נשען על הקודם וחוזר עמוק יותר בהמשך.</p></div><div className="modeSwitch"><button className={mode==='owner'?'active':''} onClick={()=>setMode('owner')}>מצב יוצר · הכל פתוח</button><button className={mode==='journey'?'active':''} onClick={()=>setMode('journey')}>מצב מסע · לפי הסדר</button></div></div><div className="sourceStatus"><span className={corpusReady?'sourceDot ready':'sourceDot'}/><strong>{corpusReady?'18 מקורות מלאים מחוברים':'מקורות נטענים'}</strong><small>{paragraphs.toLocaleString()} פסקאות · {characters.toLocaleString()} תווים · המקור נשמר ללא קיצור</small></div><div className="journeySearch"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="חפש רעיון, פרק או טקסט בתוך המסע..."/></div>{query.trim()?<section className="searchJourneyResults">{filtered.map(c=><button key={c.number} disabled={!accessible(c.number)} onClick={()=>open(c.number)}><b>{String(c.number).padStart(2,'0')}</b><div><strong>{clean(c.title)}</strong><small>{c.subtitle}</small></div></button>)}</section>:<div className="spiralMap">{worlds.map(world=>{const entries=learningPath.filter(x=>x.world===world);return <section className={'worldBand world-'+world.toLowerCase()} key={world}><div className="worldIntro"><span>{worldLabels[world]}</span><small>{entries.length} תחנות</small></div><div className="worldTrack">{entries.map((p,index)=>{const c=chapters.find(x=>x.number===p.number);const locked=!accessible(p.number);return <React.Fragment key={p.number}><button className={'journeyNode '+(locked?'locked':'')} disabled={locked} onClick={()=>open(p.number)}><span className="nodeNumber">{String(p.number).padStart(2,'0')}</span><div><small>{stageLabels[p.stage]}</small><strong>{c?clean(c.title):`פרק ${p.number}`}</strong><em>{p.accent}</em></div>{locked&&<i>נעול</i>}</button>{index<entries.length-1&&<span className="trackLine">→</span>}</React.Fragment>})}</div></section>})}</div>}<section className="spiralLegend"><div><b>לראות</b><span>ויזואל ואינטואיציה</span></div><div><b>לחוות</b><span>דוגמה או micro‑video</span></div><div><b>להבין</b><span>המודל והרציונל</span></div><div><b>לחבר</b><span>קשרים לידע קודם</span></div><div><b>ליישם</b><span>תרגיל והחלטה</span></div><div><b>להתבונן</b><span>תובנה ושכבה חדשה</span></div></section></div>
}
