import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

function readJson(file){return JSON.parse(fs.readFileSync(path.join(process.cwd(),file),'utf8'))}
function corpus(){const dir=path.join(process.cwd(),'data','corpus');const names=fs.readdirSync(dir).filter(x=>/^chapters-lossless-\d+\.b64$/.test(x)).sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]));const b64=names.map(n=>fs.readFileSync(path.join(dir,n),'utf8').trim()).join('');return JSON.parse(zlib.gunzipSync(Buffer.from(b64,'base64')).toString('utf8'))}
const norm=s=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const snippets=(chapter,terms)=>{const needles=terms.map(norm).filter(Boolean);return chapter.paragraphs.map((text,index)=>({index:index+1,text})).filter(p=>needles.some(t=>norm(p.text).includes(t))).slice(0,3)};
export default async function handler(req,res){try{const map=readJson('data/content-map.json');const chapters=corpus();if(chapters.length!==18)throw Error('corpus integrity failed');const nodes=map.chapters.map(m=>{const c=chapters.find(x=>x.number===m.id);return{id:m.id,title:c?.title||m.title,sourceFile:c?.sourceFile||'',primary:m.primary,secondary:m.secondary||[],topics:m.topics,paragraphCount:c?.paragraphCount||c?.paragraphs?.length||0,characterCount:c?.characterCount||0,evidence:snippets(c||{paragraphs:[]},m.topics)}});const seen=new Set();const edges=[];for(const m of map.chapters)for(const target of m.links||[]){const key=[m.id,target].sort((a,b)=>a-b).join('-');if(seen.has(key))continue;seen.add(key);const a=map.chapters.find(x=>x.id===m.id),b=map.chapters.find(x=>x.id===target);const shared=a.topics.filter(t=>b.topics.some(u=>norm(u).includes(norm(t))||norm(t).includes(norm(u))));edges.push({source:m.id,target,kind:'curated',sharedTopics:shared})}const topics=map.crossCuttingTopics.map(t=>({topic:t.topic,chapters:t.chapters,evidence:t.chapters.flatMap(id=>{const c=chapters.find(x=>x.number===id);return snippets(c||{paragraphs:[]},[t.topic]).map(s=>({chapter:id,...s}))}).slice(0,6)}));res.setHeader('Cache-Control','public, max-age=0, must-revalidate');return res.json({ok:true,sourceMode:'lossless-docx-text',nodes,edges,categories:map.categories,topics,stats:{documents:nodes.length,edges:edges.length,topics:topics.length,evidence:topics.reduce((n,t)=>n+t.evidence.length,0)}})}catch(e){return res.status(500).json({ok:false,error:e.message})}}
